import React, { useState, useEffect } from 'react';
import { sendMessage, onMessage } from '../services/bridge';

export const AutoCoderPanel: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [language, setLanguage] = useState('cpp');
  const [generatedCode, setGeneratedCode] = useState('');
  const [generating, setGenerating] = useState(false);
  const [logs, setLogs] = useState<string[]>([]);
  const [buildStatus, setBuildStatus] = useState<any>(null);
  const [projectName, setProjectName] = useState('');
  const [projectDescription, setProjectDescription] = useState('');

  useEffect(() => {
    const unsubCode = onMessage('codeGenerated', (data: any) => {
      setGenerating(false);
      if (data.success) {
        setGeneratedCode(data.code);
        setLogs(prev => [...prev, '✓ Code generated successfully']);
      } else {
        setLogs(prev => [...prev, '✗ Code generation failed: ' + data.message]);
      }
    });

    const unsubProject = onMessage('projectGenerated', (data: any) => {
      setGenerating(false);
      if (data.success) {
        setLogs(prev => [...prev, '✓ Full project generated!']);
        setLogs(prev => [...prev, '  Files created: ' + data.filesCreated]);
      }
    });

    const unsubStatus = onMessage('buildStatus', (data: any) => {
      setBuildStatus(data);
    });

    const unsubErrors = onMessage('errorsFixed', (data: any) => {
      setLogs(prev => [...prev, `✓ Fixed ${data.count} errors`]);
    });

    return () => {
      unsubCode();
      unsubProject();
      unsubStatus();
      unsubErrors();
    };
  }, []);

  const handleGenerateCode = () => {
    if (!prompt) {
      alert('Please enter a prompt');
      return;
    }

    setGenerating(true);
    setGeneratedCode('');
    setLogs(prev => [...prev, `Generating ${language} code...`]);
    
    sendMessage('generateCode', {
      prompt,
      language
    });
  };

  const handleGenerateProject = () => {
    if (!projectDescription) {
      alert('Please describe your project');
      return;
    }

    setGenerating(true);
    setLogs([]);
    setLogs(prev => [...prev, 'Generating full project...']);
    
    sendMessage('generateFullProject', {
      name: projectName || 'AutoGeneratedProject',
      description: projectDescription,
      languages: [language]
    });
  };

  const handleFixErrors = () => {
    setLogs(prev => [...prev, 'Running auto-fixer...']);
    sendMessage('fixAllErrors', { projectPath: '.' });
  };

  const handleRunRecursion = () => {
    setLogs(prev => [...prev, 'Starting recursion engine...']);
    sendMessage('runRecursionEngine', { projectPath: '.' });
  };

  const handleGenerateTests = () => {
    setLogs(prev => [...prev, 'Generating tests...']);
    sendMessage('generateTests', { modulePath: './src/main.cpp' });
  };

  const handleSaveCode = () => {
    if (!generatedCode) return;
    
    const filename = window.prompt('Save as:') || 'generated.' + (language === 'cpp' ? 'cpp' : language === 'python' ? 'py' : 'js');
    sendMessage('saveFile', {
      path: './src/' + filename,
      content: generatedCode
    });
  };

  return (
    <div style={styles.container}>
      <h2 style={styles.title}>🤖 ZACH Auto Coder</h2>

      {/* Code Generation */}
      <div style={styles.section}>
        <h3>Natural Language → Code</h3>
        <select 
          value={language} 
          onChange={(e) => setLanguage(e.target.value)}
          style={styles.select}
        >
          <option value="cpp">C++</option>
          <option value="python">Python</option>
          <option value="javascript">JavaScript</option>
          <option value="typescript">TypeScript</option>
          <option value="rust">Rust</option>
          <option value="csharp">C#</option>
        </select>
        
        <textarea
          placeholder="Describe what you want in natural language... e.g., 'Create a web server with REST API'"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          style={styles.textarea}
          rows={4}
        />
        
        <div style={styles.buttonRow}>
          <button
            onClick={handleGenerateCode}
            disabled={generating}
            style={{
              ...styles.button,
              opacity: generating ? 0.5 : 1
            }}
          >
            {generating ? '⏳ Generating...' : '✨ Generate Code'}
          </button>
          
          {generatedCode && (
            <button onClick={handleSaveCode} style={styles.button}>
              💾 Save Code
            </button>
          )}
        </div>

        {generatedCode && (
          <div style={styles.codePreview}>
            <pre style={styles.codeBlock}>{generatedCode}</pre>
          </div>
        )}
      </div>

      {/* Full Project Generation */}
      <div style={styles.section}>
        <h3>Full Project Generator</h3>
        <input
          type="text"
          placeholder="Project Name"
          value={projectName}
          onChange={(e) => setProjectName(e.target.value)}
          style={styles.input}
        />
        <textarea
          placeholder="Describe your entire project... e.g., 'A task management app with user authentication, database, and REST API'"
          value={projectDescription}
          onChange={(e) => setProjectDescription(e.target.value)}
          style={styles.textarea}
          rows={3}
        />
        <button
          onClick={handleGenerateProject}
          disabled={generating}
          style={{
            ...styles.button,
            backgroundColor: '#4CAF50',
            opacity: generating ? 0.5 : 1
          }}
        >
          {generating ? '⏳ Generating Project...' : '🚀 Generate Full Project'}
        </button>
      </div>

      {/* Auto-Fixer & Tools */}
      <div style={styles.section}>
        <h3>Auto-Fixer & Tools</h3>
        <div style={styles.toolGrid}>
          <button onClick={handleFixErrors} style={styles.toolButton}>
            🔧 Fix All Errors
          </button>
          <button onClick={handleRunRecursion} style={styles.toolButton}>
            🔄 Run Recursion Engine
          </button>
          <button onClick={handleGenerateTests} style={styles.toolButton}>
            🧪 Generate Tests
          </button>
          <button onClick={() => sendMessage('formatCode', {})} style={styles.toolButton}>
            💅 Format Code
          </button>
        </div>
      </div>

      {/* Build Status */}
      {buildStatus && (
        <div style={styles.section}>
          <h3>Build Status</h3>
          <div style={styles.statusGrid}>
            <div style={styles.statusItem}>
              <span>Features</span>
              <strong>{buildStatus.completedFeatures}/{buildStatus.totalFeatures}</strong>
            </div>
            <div style={styles.statusItem}>
              <span>Errors</span>
              <strong style={{color: buildStatus.totalErrors === 0 ? '#4CAF50' : '#f44336'}}>
                {buildStatus.totalErrors}
              </strong>
            </div>
            <div style={styles.statusItem}>
              <span>Completion</span>
              <strong>{buildStatus.completionPercent.toFixed(1)}%</strong>
            </div>
          </div>
          <div style={styles.progressBar}>
            <div style={{
              ...styles.progressFill,
              width: `${buildStatus.completionPercent}%`
            }}></div>
          </div>
        </div>
      )}

      {/* Logs */}
      <div style={styles.section}>
        <h3>Activity Log</h3>
        <div style={styles.logsContainer}>
          {logs.map((log, index) => (
            <div key={index} style={styles.logLine}>
              [{new Date().toLocaleTimeString()}] {log}
            </div>
          ))}
          {logs.length === 0 && (
            <p style={styles.emptyText}>No activity yet</p>
          )}
        </div>
      </div>
    </div>
  );
};

const styles: { [key: string]: React.CSSProperties } = {
  container: {
    padding: '20px',
    height: '100%',
    overflowY: 'auto',
    backgroundColor: '#1e1e1e',
    color: '#ffffff'
  },
  title: {
    marginTop: 0,
    marginBottom: '20px',
    fontSize: '28px',
    fontWeight: 'bold'
  },
  section: {
    marginBottom: '30px',
    padding: '15px',
    backgroundColor: '#252526',
    borderRadius: '5px'
  },
  select: {
    width: '100%',
    padding: '10px',
    marginBottom: '10px',
    backgroundColor: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: '3px',
    color: '#ffffff',
    fontSize: '14px'
  },
  input: {
    width: '100%',
    padding: '10px',
    marginBottom: '10px',
    backgroundColor: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: '3px',
    color: '#ffffff',
    fontSize: '14px'
  },
  textarea: {
    width: '100%',
    padding: '10px',
    marginBottom: '10px',
    backgroundColor: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: '3px',
    color: '#ffffff',
    fontSize: '14px',
    fontFamily: 'Consolas, monospace',
    resize: 'vertical'
  },
  buttonRow: {
    display: 'flex',
    gap: '10px',
    marginBottom: '15px'
  },
  button: {
    padding: '12px 24px',
    backgroundColor: '#007acc',
    border: 'none',
    borderRadius: '3px',
    color: '#ffffff',
    fontSize: '14px',
    cursor: 'pointer',
    fontWeight: 'bold'
  },
  codePreview: {
    marginTop: '15px'
  },
  codeBlock: {
    backgroundColor: '#1e1e1e',
    padding: '15px',
    borderRadius: '3px',
    border: '1px solid #555',
    fontSize: '13px',
    fontFamily: 'Consolas, monospace',
    color: '#d4d4d4',
    overflowX: 'auto',
    maxHeight: '400px',
    overflowY: 'auto'
  },
  toolGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '10px'
  },
  toolButton: {
    padding: '10px',
    backgroundColor: '#3c3c3c',
    border: '1px solid #555',
    borderRadius: '3px',
    color: '#ffffff',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'background-color 0.2s'
  },
  statusGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '15px',
    marginBottom: '15px'
  },
  statusItem: {
    padding: '15px',
    backgroundColor: '#3c3c3c',
    borderRadius: '5px',
    textAlign: 'center'
  },
  progressBar: {
    width: '100%',
    height: '20px',
    backgroundColor: '#555',
    borderRadius: '10px',
    overflow: 'hidden'
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
    transition: 'width 0.3s ease'
  },
  logsContainer: {
    maxHeight: '300px',
    overflowY: 'auto',
    backgroundColor: '#1e1e1e',
    padding: '10px',
    borderRadius: '3px',
    border: '1px solid #555'
  },
  logLine: {
    fontSize: '12px',
    fontFamily: 'Consolas, monospace',
    color: '#cccccc',
    marginBottom: '5px'
  },
  emptyText: {
    textAlign: 'center',
    color: '#888',
    padding: '20px'
  }
};

export default AutoCoderPanel;
